Gate a use statement by algorithm_group_by instead of rows
This resolves a build issue that existed prior to this commit:

$ cargo build --no-default-features --features dtype-i8,rows
<snip>
error[E0432]: unresolved import `crate::frame::group_by`
  --> crates/polars-core/src/series/series_trait.rs:51:23
   |
51 |     use crate::frame::group_by::GroupsProxy;
   |                       ^^^^^^^^ could not find `group_by` in `frame`

Fixes: #11373
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>